upgrade to ff/group 0.13.0
scroll-tech/poseidon-circuit pull request #13
Opened 2023-03-13 23:57 UTC by zhenfeizhang

2023-03-22 12:01 UTC, naure requested changes
LGTM besides couple of comments.

2023-03-22 13:58 UTC, naure commented
I resolved the conflict with recent changes in `main`. Please let me know whether that works for you.

2023-04-08 07:10 UTC, noel2004 commented
Now I have merged the main branch (with septidon refactoring) in it and the code seems work now

For the special dependency of halo2 lib (`halo2-ecc-snark-verifier-0220`), I think it is still not able to be merged into main branch. Just kept it here until our halo2 lib dependency become stable

2023-04-08 07:18 UTC, noel2004 commented on rust-toolchain
> +nightly
I think this should work.

2023-10-16 18:47 UTC, zhenfeizhang commented
replaced with #29

2023-10-16 18:47 UTC, closed without merging