feat: use assign_regions api to speed up hash function
scroll-tech/poseidon-circuit pull request #24
Opened 2023-05-28 08:20 UTC by alannotnerd

See #23

2023-06-12 13:39 UTC, kunxian-xia requested changes
Overall LGTM!

2023-06-12 14:06 UTC, kunxian-xia commented
@noel2004 Is it true that each `((inp, control), check)` occupies **exactly one** row in the `fill_hash_tbl_body` region? https://github.com/scroll-tech/poseidon-circuit/blob/89e9c0456f0fa00d49cd7920c6b437c66b48db17/src/hash.rs#L507

2023-06-12 14:42 UTC, noel2004 commented
> @noel2004 Is it true that each `((inp, control), check)` occupies **exactly one** row in the `fill_hash_tbl_body` region?
> 
> https://github.com/scroll-tech/poseidon-circuit/blob/89e9c0456f0fa00d49cd7920c6b437c66b48db17/src/hash.rs#L507

Yes. Each entry occupies one row.

2023-06-12 14:43 UTC, kunxian-xia commented
There remains two problems to be solved:
1. parallelize all these `permute` to get final state (10s out of 60s),
2. reduce 1st phase of `fill_hash_tbl_body_partial` to 0.

2023-06-13 10:21 UTC, kunxian-xia approved these changes

2023-06-13 11:45 UTC, alannotnerd commented
```
[2023-06-13T11:42:40Z INFO  halo2_proofs::circuit::floor_planner::single_pass] 25 sub_regions of hash table 2nd pass synthesis took 966.003307ms
[2023-06-13T11:42:40Z INFO  poseidon_circuit::hash] hash table parallel version took 972.602083ms
[2023-06-13T11:42:40Z INFO  halo2_proofs::circuit::floor_planner::single_pass] 24 sub_regions of permute state 2nd pass synthesis took 41.37005ms
[2023-06-13T11:42:40Z INFO  poseidon_circuit::hash] final state took 834.965283ms
```

2023-06-18 09:54 UTC, kunxian-xia commented
We got the following stats when testing in scroll-zkevm (tested on a machine with 128 threads):
```
[2023-06-16T06:58:10Z INFO  poseidon_circuit::hash] hash table parallel version took 445.565348ms
[2023-06-16T07:00:47Z INFO  poseidon_circuit::hash] hash table parallel version took 452.829501ms
[2023-06-16T07:03:29Z INFO  poseidon_circuit::hash] hash table parallel version took 490.576667ms
[2023-06-16T06:58:10Z INFO  poseidon_circuit::hash] final state took 105.097895ms
[2023-06-16T07:00:47Z INFO  poseidon_circuit::hash] final state took 103.493175ms
[2023-06-16T07:03:29Z INFO  poseidon_circuit::hash] final state took 110.563839ms
```

2023-07-20 09:49 UTC, noel2004 commented
Has been merged into `main`

2023-07-20 09:49 UTC, closed without merging